In [1]:
import time
import logging
import numpy as np

In [2]:
from tictactoe import RandomAI,Board,Judge,check_win
from random import choice

## Rule
* Empty： - (0) , Player(you)： O (1) , Opponent：X (-1)
* Board Index：
| | | |
| - | - | - |
| 0 | 1 | 2 |
| 3 | 4 | 5 |
| 6 | 7 | 8 |

In [3]:
def profile(func):
    """
    －This function helps you to avoid wrong algorithm that cost you too many time
    －Change the limit as you wish！
    """
    def wrap(*args, **kwargs):
        limit = 10
        s = time.time()
        result = func(*args, **kwargs)
        duration = time.time() - s
        if duration > limit:
            logging.warning(f"Time Limit Exceeded: {duration}")
        logging.info(f"using {duration} sec")
        return result
    return wrap

In [77]:
class Node:
    def __init__(self, board_status):
        self.board_status = board_status
        self.child = []
        self.parrent = None
        
    def add_child(self, board_status):
        self.child.append(Node(board_status))
        self.child[-1].parrent = self
        
    

In [79]:
a= Node(np.zeros(9))
a.add_child(np.ones(9))
it = a.child[0]
it.parrent.board_status

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [98]:
class Tree:
    def __init__(self):
        self.root = Node(np.zeros(9))
        self.current = self.root
        self.flag = 1
        self.build(self.current)
        
    def get_valid_move(self, board_status):
        return np.where(board_status == 0)[0]
        
    def forward(self, board_status):
        for i in self.current.child:
            if i.board_status == board_status:
                self.current = i
                self.flag*=-1
                break
                
    def build(self, Node):
        for i in get_valid_move(Node.board_status):
            cp = Node.board_status.copy()
            cp[i] = self.flag
            Node.add_child(cp)
            self.build(Node.child[-1])
            
        

In [99]:
tree = Tree()

In [103]:
tree.current.child[6].child[7].board_status

array([0., 0., 0., 0., 0., 0., 1., 0., 1.])

In [11]:
class Player:
    def __init__(self):
        self.name = "Player"
     
    def get_valid_move(self, board_status):
        return np.where(board_status == 0)[0]

    
    def minimax(self,*kwarg):
        """
        Implement your own minmax algorithm here!
        """
        pass
        
        
    def alphabeta_move(self,*kwarg):
        """
        ["Optional"] Implement your own alphabeta algorithm here!
        """
        pass
    
    def random_move(self,board_status)->int:
        return choice(self.get_valid_move(board_status))
    
    @profile
    def move(self, board_status)->int:
        """
        - Here we show you the result that use random move as strategy
        """
        return self.random_move(board_status)

In [9]:
NUM_RUNS = [-1,1]*50

In [10]:
game = Board(Player(),RandomAI(), Judge(who_Turn=-1))
print("PLAYER：　Ｏ　AI：Ｘ   Space：-　"+"\n")
start = time.time()
for i in NUM_RUNS:
    game.judge.who_Turn = i
    game.play()
end = time.time()
print(f"Time cost --- {end - start}")

PLAYER：　Ｏ　AI：Ｘ   Space：-　

PLAYER　WIN 1:
[['O' 'O' 'O']
 ['X' '-' 'X']
 ['X' 'O' 'X']]

PLAYER　WIN 2:
[['X' 'X' '-']
 ['O' 'O' 'O']
 ['O' '-' 'X']]

AI WIN 1:
[['X' 'X' 'X']
 ['O' 'O' '-']
 ['O' 'X' '-']]

AI WIN 2:
[['X' 'X' 'X']
 ['O' 'O' 'X']
 ['O' 'O' '-']]

AI WIN 3:
[['O' 'X' '-']
 ['X' 'X' 'O']
 ['-' 'X' 'O']]

Tie 1:
[['O' 'O' 'X']
 ['X' 'O' 'O']
 ['O' 'X' 'X']]

AI WIN 4:
[['X' 'O' 'X']
 ['O' 'X' 'O']
 ['X' 'X' 'O']]

AI WIN 5:
[['O' 'X' '-']
 ['O' 'X' 'O']
 ['X' 'X' 'O']]

PLAYER　WIN 3:
[['-' 'X' 'X']
 ['O' 'O' 'O']
 ['X' 'X' 'O']]

PLAYER　WIN 4:
[['O' 'O' 'X']
 ['O' '-' '-']
 ['O' 'X' 'X']]

AI WIN 6:
[['X' 'O' 'O']
 ['O' 'O' 'X']
 ['X' 'X' 'X']]

PLAYER　WIN 5:
[['O' 'O' 'O']
 ['O' 'X' 'X']
 ['O' 'X' 'X']]

PLAYER　WIN 6:
[['X' 'X' 'O']
 ['X' 'X' 'O']
 ['O' '-' 'O']]

PLAYER　WIN 7:
[['O' 'O' 'O']
 ['X' '-' '-']
 ['X' 'X' 'O']]

PLAYER　WIN 8:
[['O' 'X' 'O']
 ['O' '-' 'X']
 ['O' 'X' 'X']]

AI WIN 7:
[['O' 'O' 'X']
 ['O' '-' 'O']
 ['X' 'X' 'X']]

PLAYER　WIN 9:
[['O' 'X' 'X']
 ['

In [31]:
print(f"You Win {game.judge.n_player_win} out of 100 games")
print(f"You Lose {game.judge.n_player_lose} out of 100 games")
print(f"You Tie {game.judge.tie} out of 100 games")
# del game

You Win 33 out of 100 games
You Lose 28 out of 100 games
You Tie 39 out of 100 games


In [8]:
print(time.time())

1636520571.2295747


In [29]:
np.where(np.zeros((9,)) == 0)[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])